### PR TITLE
Add Codeclimate to GitHub Action

### PR DESCRIPTION
**Pull request by dingdayu**
use [codeclimate](https://codeclimate.com/)

### CODE REVIEW

**Comment by dingdayu** [comment]
@huan 我在尝试引入代码评估，[codeclimate](https://codeclimate.com)  这是一个类似  SonarSource 的平台，免费服务于开源项目，在 Go 里面提供了 goline/Gofmt/govet plugins，同时提供了 `Cognitive Complexity`,`Cyclomatic Complexity`,`Duplication` 检测功能，我们可以尝试引入这个工具。

如果你觉得可以尝试的话，需要进行项目授权，详细的可以在 [getting-started-with-code-climate](https://docs.codeclimate.com/docs/getting-started-with-code-climate) 获取帮助。

**Comment by dingdayu** [comment]
I tried `appveyor` and` travis-ci` and found that most of the functions are in `Github Action` with similar functions, for example:` Win` System, `Arm` CPU.

Later we can introduce multi-platform testing, which may not help much at this time, but `codeclimate ` is not the same, it can help us improve the code.

**Comment by huan** [comment]
Hi @dingdayu , Thank you very much for adding the CodeClimate service to our repository so that it can help us to check the code quality automatically!

I have tried to enable it but it seems that it's a paid service only.

I will try to find out the support for open source project from it today later, please let me know if you have more information about how to use it with our repository, appreciate it!

**Comment by dingdayu** [comment]
> Hi @dingdayu , Thank you very much for adding the CodeClimate service to our repository so that it can help us to check the code quality automatically!
> 
> I have tried to enable it but it seems that it's a paid service only.
> 
> I will try to find out the support for open source project from it today later, please let me know if you have more information about how to use it with our repository, appreciate it!

my use, it has been free for open source.

**Comment by huan** [comment]
Done.

Please have a look at https://codeclimate.com/github/wechaty/go-wechaty and let me know if there's anything need to be fixed.

**Comment by dingdayu** [comment]
@huan Hi,根据 Action  的日志看，我们还缺少一个 `CC_TEST_REPORTER_ID` 环境变量，在 GitHub 中，我们可以在项目的 [Settings -> Secrets](https://github.com/wechaty/go-wechaty/settings/secrets) 中配置.

891587694430_ pic

**Comment by huan** [comment]
Added.

Please feel free to let me know if there's anything that needs me to do, and thank you very much for setting the CodeClimate up!

**Comment by dingdayu** [comment]
@dchaofei @SilkageNet 这个 PR 由于引入了代码质量评估，所以需要新的环境变量，@huan 配置了相关环境变量，但由于Github 的安全策略，在旧的 PR 中无法直接使用，导致无法正常通过CI 检测。

@huan 提议大家帮我进行 `approve` 然后再帮我手动 合并。

**Comment by huan** [comment]
Thank you all for improving the code quality for our Go Wechaty project!

**Comment by huan** [comment]
It seems the CI has been passed after this PR was merged. Cheers!

**Pull request merged**
