### PR TITLE
add api & fix bug

### PR DESCRIPTION
**Pull request by dchaofei**
- add `func (w *Wechaty) Puppet() wp.IPuppetAbstract`
- add `func (w *Wechaty) UserSelf() _interface.IContactSelf`

- fix bug

### CODE REVIEW

**Review by dingdayu — APPROVED** [review]

**Comment by dchaofei** [comment]
@wechaty/go 请帮助 merge 这个 pr

**Comment by dchaofei** [comment]
@huan @SilkageNet 请帮助 merge 这个 pr

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
@dchaofei Thank you very much for the fix!

It seems this PR has waited for a long time, so I change the required approvements from 2 to 1 to make the process to be simple, and I have also changed your role from maintainer to admin so that you will be able to merge a PR whenever you believe it's necessary before it has been approved.

Please help our community to keep the Go Wechaty to be good, appreciate all the great works that you did for the Go Wechaty!

**Comment by dchaofei** [comment]
> @dchaofei Thank you very much for the fix!
> 
> It seems this PR has waited for a long time, so I change the required approvements from 2 to 1 to make the process to be simple, and I have also changed your role from maintainer to admin so that you will be able to merge a PR whenever you believe it's necessary before it has been approved.
> 
> Please help our community to keep the Go Wechaty to be good, appreciate all the great works that you did for the Go Wechaty!

感谢放开这个权限，相信 go wechaty 会更好

**Pull request merged**
