### PR TITLE
optimization

### PR DESCRIPTION
**Pull request by dchaofei**

### CODE REVIEW

**Comment by dingdayu** [comment]
@dchaofei Please update upstream and fix the [issues](https://codeclimate.com/github/wechaty/go-wechaty/pull/57)

**Comment by dchaofei** [comment]
> @dchaofei Please update upstream and fix the [issues](https://codeclimate.com/github/wechaty/go-wechaty/pull/57)

fixed a part of it, but some don’t seem to need fix

**Comment by dchaofei** [comment]
@dingdayu I think this is not necessary to fix, can you talk about your opinion?  https://codeclimate.com/github/wechaty/go-wechaty/pull/57

**Comment by dingdayu** [comment]
> @dingdayu I think this is not necessary to fix, can you talk about your opinion?  https://codeclimate.com/github/wechaty/go-wechaty/pull/57


Yes, there is an opportunity to update the codeclimate configuration and increase the threshold.

**Pull request merged**
