### PR TITLE
fix: examples maintain

### PR DESCRIPTION
**Pull request by yy1987316**
examples maintain
1. fix example imports
2. start service with using DaemonStart() instead of Start()
3. correct if conditions return in OnMessage handler
4. correct code fragment of replying image
5. add code fragment of replying url link

### CODE REVIEW

**Comment by huan** [comment]
## Wechaty Contributors Nomination

Link to https://github.com/wechaty/PMC/issues/16

**Comment by yy1987316** [comment]
plz let me know if anything blocks this mr from being merged @huan

**Comment by dchaofei** [comment]
我测试了下你的 pr, 发送图片会失败

**Comment by dchaofei** [comment]
> 

这是 go-wechaty 的 bug，我已经修复 https://github.com/wechaty/go-wechaty/pull/106

**Comment by dchaofei** [comment]
非常感谢你的 pr，我已经 merge

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited yy1987316 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Pull request merged**
