### PR TITLE
style: rename interface `Accessory` to `IAccessory`

### PR DESCRIPTION
**Pull request by simpleapples**
i found that all interfaces have been named `IName` expect `Accessory`, so i renamed it.

### CODE REVIEW

**Comment by dingdayu** [comment]
@dchaofei Please help review this PR.

**Comment by dchaofei** [comment]
@simpleapples Thank you very much pr, it would be better if `wechaty/interface/wechaty.go:4` can be changed together.

**Comment by simpleapples** [comment]
@dchaofei You're welcome.
I have renamed `Wechaty` to `IWechaty`, please review the code, thx.

**Comment by dchaofei** [comment]
@dingdayu Please help review this PR.

**Comment by dingdayu** [comment]
@simpleapples HI，Sorry there is no immediate processing.

When I review the PR, I found some minor problems, the [codeclimate](https://codeclimate.com/github/wechaty/go-wechaty/pull/58)  failed.

I read it because the code is not formatted by fmt and some exported functions are not commented.

If you need help, you can get my contact information directly by email (614422099@qq.com)

**Comment by simpleapples** [comment]
@dingdayu Hi, I have fixed all issues except the 'similar blocks' issue. Please review it. 

Thank you.

**Comment by huan** [comment]
Hi @simpleapples ,

Thank you for the contribution! I have invited you to join our Wechaty Contributors team on GitHub, please accept it by following the below message:

> You've invited Zhiya Zang to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

And we have a WeChat Group for our contributors, please contact @lijiarui and she will help you to join.

Cheers!

**Comment by simpleapples** [comment]
Hi, @huan ,

Got it, thank you.

**Comment by huan** [comment]
You are welcome!

**Comment by lijiarui** [comment]
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://github.com/wechaty/wechaty/wiki/Contributors), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

**Pull request merged**
