### PR TITLE
Add memory_card

### PR DESCRIPTION
**Pull request by dchaofei**
The simple implementation of memory-card can not be as complicated as the TS version at present. The goal is to run the go wechaty demo first, and then iterate as needed later.

Question 1: which directory is suitable for such a toolkit?

### CODE REVIEW

**Comment by huan** [comment]
The `MemoryCard` plays a very important part of the Wechaty bot system, and it will be enhanced to be more fit on our cloud service in the near future.

Your PR is a very good start of the Go version of MemoryCard.

### Answer your question

> Question 1: which directory is suitable for such a toolkit?

Answer: The current path where you put the memory-card.go (wechaty-puppet/memory-card/memory_card.go) is good. 

All modules that were dependencied by Wechaty can be put into the wechaty-puppet/ submodule, and we can split it out in the future.

**Comment by huan** [comment]
BTW: Thank you for accepting my invitation and joined the GitHub Wechaty Org!

Please add my WeChat 918999 so that we can talk on WeChat. Cheers!

**Comment by dingdayu** [comment]
great

**Comment by huan** [comment]
Congratulations on having our Go version or MemoryCard component! (and the tests!)

**Pull request merged**
